import Navbar from "@/components/navbar";
import Popular from "@/components/popular";
import TopRated from "@/components/topRated";
import Link from "next/link";
export const metadata = {
  title: "Movie",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <main>
        <Navbar bg="backdrop-blur-sm bg-primary/80" position="sticky" />
        <section id="Popular">
          <Link href="/Popular/1">
            <h1
              data-aos="zoom-in-right"
              data-aos-anchor-placement="bottom-bottom"
              className="ml-auto mr-2 sm:mr-20 text-center mt-10 bg-primary w-24 rounded-lg shadow-md hover:bg-indigo-500">
              Popular {">>"}
            </h1>
          </Link>
          <div className=" mx-10 my-4 grid md:grid-cols-2 xl:grid-cols-3 dekstop:grid-cols-6 gap-4">
            <Popular />
          </div>
        </section>
        <section id="TopRated">
          <Link href="TopRated/1">
            <h1
              data-aos="zoom-in-right"
              data-aos-anchor-placement="bottom-bottom"
              className="ml-auto mr-2 sm:mr-20 text-center mt-10 bg-primary w-24 rounded-lg shadow-md hover:bg-indigo-500">
              Top Rated {">>"}
            </h1>
          </Link>
          <div className="mx-10 my-4 grid md:grid-cols-2 xl:grid-cols-3 dekstop:grid-cols-6 gap-4">
            <TopRated />
          </div>
        </section>
      </main>
    </>
  );
}
